---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: codegen-test-nov6-existingmodel
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-test-nov6-existingmodel 
  name: codegen-test-nov6-existingmodel
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi