apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-dsp-codegen-test-nov6-existingmodel-gitops
spec:  
  template:         
    metadata:
      name: initialize-dsp-codegen-test-nov6-existingmodel-gitops
    spec:  
      serviceAccountName: codegen-test-nov6-existingmodel-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest

        command:
        - /bin/bash
        - -c
        - |
          # Wait for the Image Stream creation job to finish
          echo "Wait for the Image Stream job"
          oc wait --for=condition=complete job/create-imagestream-codegen-test-nov6-existingmodel-gitops
          echo "Done"
          
          # Wait for the Namespace initialize job to finish
          echo "Wait for the Namespace job"
          oc wait --for=condition=complete job/initialize-namespace-codegen-test-nov6-existingmodel-gitops
          echo "Done"

          # Label the namespace as a DataScienceProject
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc label ns $NS opendatahub.io/dashboard=true --overwrite

          # Retrieve the UID for the notebook SA, and mark the notebook as owned by it for garbage collection purposes
          SA_UID=$(oc get sa codegen-test-nov6-existingmodel-dsp-job -o json | jq -r .metadata.uid)
          echo "$SA_UID"
          cat <<EOF | oc apply -f -
          apiVersion: kubeflow.org/v1
          kind: Notebook
          metadata:
            annotations:
              notebooks.opendatahub.io/inject-oauth: 'true'
              opendatahub.io/image-display-name: Minimal Python
              opendatahub.io/accelerator-name: ''
              openshift.io/description: ''
              openshift.io/display-name: codegen-test-nov6-existingmodel-notebook
              notebooks.opendatahub.io/last-image-selection: 's2i-minimal-notebook:2024.1'
              notebooks.opendatahub.io/last-size-selection: Small
            name: codegen-test-nov6-existingmodel-notebook
            namespace: rhdh-app
            ownerReferences:
              - apiVersion: v1
                kind: ServiceAccount
                name: codegen-test-nov6-existingmodel-dsp-job
                uid: $SA_UID
            labels:
              app: codegen-test-nov6-existingmodel-notebook
              opendatahub.io/dashboard: 'true'
              opendatahub.io/odh-managed: 'true'
          spec:
            template:
              spec:
                affinity: {}
                containers:
                  - resources:
                      limits:
                        cpu: '2'
                        memory: 8Gi
                      requests:
                        cpu: '1'
                        memory: 8Gi
                    readinessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /notebook/rhdh-app/codegen-test-nov6-existingmodel-notebook/api
                        port: notebook-port
                        scheme: HTTP
                      initialDelaySeconds: 10
                      periodSeconds: 5
                      successThreshold: 1
                      timeoutSeconds: 1
                    name: codegen-test-nov6-existingmodel-notebook
                    livenessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /notebook/rhdh-app/codegen-test-nov6-existingmodel-notebook/api
                        port: notebook-port
                        scheme: HTTP
                      initialDelaySeconds: 10
                      periodSeconds: 5
                      successThreshold: 1
                      timeoutSeconds: 1
                    env:
                      - name: MODEL_ENDPOINT_BEARER
                        valueFrom:
                          secretKeyRef:
                            name: existing-model
                            key: api-key
                      - name: NOTEBOOK_ARGS
                        value: |-
                          --ServerApp.port=8888
                                            --ServerApp.token=''
                                            --ServerApp.password=''
                                            --ServerApp.base_url=/notebook/rhdh-app/codegen-test-nov6-existingmodel-notebook
                                            --ServerApp.quit_button=False
                      - name: JUPYTER_IMAGE
                        value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/custom-sqlite3-odh-minimal-notebook-container:v2-2024a-20240523-sqlite3'
                    envFrom:
                    - configMapRef:
                        name: codegen-test-nov6-existingmodel-model-config
                    ports:
                      - containerPort: 8888
                        name: notebook-port
                        protocol: TCP
                    imagePullPolicy: Always
                    volumeMounts:
                      - mountPath: /opt/app-root/src
                        name: codegen-test-nov6-existingmodel-notebook
                      - mountPath: /dev/shm
                        name: shm
                    image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/custom-sqlite3-odh-minimal-notebook-container:v2-2024a-20240523-sqlite3'
                    workingDir: /opt/app-root/src
                enableServiceLinks: false
                serviceAccountName: codegen-test-nov6-existingmodel-notebook
                volumes:
                  - name: codegen-test-nov6-existingmodel-notebook
                    persistentVolumeClaim:
                      claimName: codegen-test-nov6-existingmodel-notebook-rhoai
                  - emptyDir:
                      medium: Memory
                    name: shm
          ---
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            annotations:
              openshift.io/display-name: codegen-test-nov6-existingmodel-notebook-rhoai
            name: codegen-test-nov6-existingmodel-notebook-rhoai
            ownerReferences:
              - apiVersion: v1
                kind: ServiceAccount
                name: codegen-test-nov6-existingmodel-dsp-job
                uid: $SA_UID
            labels:
              opendatahub.io/dashboard: 'true'
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            volumeMode: Filesystem
          EOF
          
      restartPolicy: Never